// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatCareManagement.Infrastucture.Persistance.Data;

#nullable disable

namespace PetCareManagement.Infrastucture.Migrations
{
    [DbContext(typeof(PetCareDbContext))]
    [Migration("20251128095043_initaldb")]
    partial class initaldb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Attachment", b =>
                {
                    b.Property<int>("AttachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttachId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.EventAttachment", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("AttachId")
                        .HasColumnType("int");

                    b.Property<int?>("AttachmentAttachId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalEventEventId")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("AttachmentAttachId");

                    b.HasIndex("MedicalEventEventId");

                    b.ToTable("eventAttachments");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.MedicalEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextFollowupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("PetId");

                    b.ToTable("MedicalEvents");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Pets", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("_refreshTokens");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int?>("PetsPetId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ReminderId");

                    b.HasIndex("PetsPetId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.WeightHistory", b =>
                {
                    b.Property<int>("WhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WhId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int?>("PetsPetId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("WhId");

                    b.HasIndex("PetsPetId");

                    b.ToTable("WeightHistories");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.EventAttachment", b =>
                {
                    b.HasOne("PetCareManagement.Domain.Entity.Attachment", "Attachment")
                        .WithMany("Links")
                        .HasForeignKey("AttachmentAttachId");

                    b.HasOne("PetCareManagement.Domain.Entity.MedicalEvent", "MedicalEvent")
                        .WithMany("Attachments")
                        .HasForeignKey("MedicalEventEventId");

                    b.Navigation("Attachment");

                    b.Navigation("MedicalEvent");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.MedicalEvent", b =>
                {
                    b.HasOne("PetCareManagement.Domain.Entity.Pets", "Pet")
                        .WithMany("MedicalEvents")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Pets", b =>
                {
                    b.HasOne("PetCareManagement.Domain.Entity.User", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.RefreshToken", b =>
                {
                    b.HasOne("PetCareManagement.Domain.Entity.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Reminder", b =>
                {
                    b.HasOne("PetCareManagement.Domain.Entity.Pets", null)
                        .WithMany("Reminders")
                        .HasForeignKey("PetsPetId");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.WeightHistory", b =>
                {
                    b.HasOne("PetCareManagement.Domain.Entity.Pets", null)
                        .WithMany("WeightHistory")
                        .HasForeignKey("PetsPetId");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Attachment", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.MedicalEvent", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.Pets", b =>
                {
                    b.Navigation("MedicalEvents");

                    b.Navigation("Reminders");

                    b.Navigation("WeightHistory");
                });

            modelBuilder.Entity("PetCareManagement.Domain.Entity.User", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
